<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '% скидки' => '',
    'Are you sure you want to delete this item?' => '',
    'ID' => '',
    'ID Заказа' => '',
    'ID Помокода' => '',
    'ID Промокода' => '',
    'ID Экземпляра модели' => '',
    'ID Экземпляра условия' => '',
    'Reset' => '',
    'Search' => '',
    'Выберите период:' => '',
    'Дата использования' => 'Data',
    'Доля промокода в заказах' => '',
    'За 30 дней' => '',
    'За все время' => '',
    'Идентификатор пользователя' => '',
    'Использовано пользователем' => '',
    'История использований' => 'Naudojimo istorija',
    'Кем использован' => 'Naudotojas',
    'Модель' => '',
    'Название' => '',
    'Номер заказа' => 'Užsakymo nr.',
    'С 1 числа' => '',
    'Средняя стоимость' => '',
    'Статистика за период' => '',
    'Статистика по промокодам' => '',
    'Статистика по промокодам за период' => '',
    'Сумма' => 'Suma',
    'Сумма использования' => '',
    'Delete' => 'Ištrinti',
    'Promo Codes' => 'Nuolaidų kodai',
    'Update' => 'Pakeisti',
    'Активно' => 'Aktyvus',
    'Активность' => 'Aktyvumas',
    'Ваша скидка: ' => 'Jūsų nuolaida: ',
    'Введите промокод' => 'Įveskite nuolaidų kodą',
    'Выберите дату истечения срока действия промокода' => 'Nurodykite kodo galiojimo pabaigos datą',
    'Выберите тип предоставляемой промокодом скидки' => 'Pasirinkite nuolaidos rūšį',
    'Выберите тип скидки промокода:' => 'Pasirinkite nuolaidos rūšį',
    'Дата истечения промокода' => 'Galiojimo pabaiga',
    'До' => 'Iki',
    'Добавить промокод' => 'Pridėti kodą',
    'Задайте процент или сумму' => 'Įveskite procentą ar dydį',
    'Здесь задается количество использований промокода' => 'Nurodykite galimų naudojimų skaičių',
    'Значение скидки' => 'Nuolaidos dydis',
    'Изменить промокод: {name}' => 'Pakeisti nuolaidų kodą: {name}',
    'Код' => 'Kodas',
    'Количество использований' => 'Naudojimų skaičius',
    'Конечная сумма' => 'Galutinė suma',
    'Название кода(акции)' => 'Pavadinimas',
    'Накопительная скидка' => 'Kaupiamoji nuolaida',
    'Начальная сумма' => 'Pradinė suma',
    'Неактивно' => 'Neaktyvus',
    'Описание' => 'Aprašymas',
    'От' => 'Nuo',
    'Пользователь' => 'Naudotojas',
    'Прикрепить только к:' => 'Pridėti tik prie: ',
    'Промокод' => 'Nuolaidų kodas',
    'Промокод не действителен' => 'Negaliojantis kodas',
    'Промокод не найден' => 'Nuolaidų kodas nerastas',
    'Промокод применен, скидка ' => 'Nuolaidų kodas pritaikytas, nuolaida ',
    'Промокод удален!' => 'Nuolaidų kodas deaktivuotas!',
    'Промокоды' => 'Nuolaidų kodai',
    'Процент скидки' => 'Procentas',
    'Сохранить' => 'Išsaugoti',
    'Срок истечения' => 'Galiojimo pabaiga',
    'Статус' => 'Būsena',
    'Сумма скидки' => 'Suma',
    'Тип скидки промокода' => 'Nuolaidos rūšis',
    'руб.' => 'rub.',
];
